name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: prepare
      run: |
        git submodule update --init --recursive
        mkdir -p build
        cd build
        cmake ..
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: build
      run: |
        cd build
        dir
        msbuild wil_gacla.sln
    - name: check
      run: |
        cd build
    - name: package
      run: |
        cd build
    - name: archive results
      uses: actions/upload-artifact@v1
      with:
        name: packages
        path: build/win64/Debug
